-d D:\proiecte\RVCORE\YVRZ-V\impl\gwsynthesis\YVRZ-V.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst D:\proiecte\RVCORE\YVRZ-V\src\YVRZ-V.cst
-cfg D:\proiecte\RVCORE\YVRZ-V\impl\pnr\device.cfg
-sdc D:\proiecte\RVCORE\YVRZ-V\src\YVRZ-V.sdc
-bit
-tr
-ph
-warning_all
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 2
-route_option 1
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
